@baseUrl = http://localhost:3333

### Post
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name":"Bruno S. Duarte",
  "email": "brunosdua@dev.br",
  "password": "12345"
}

### @queue
GET {{baseUrl}}/queue

### @/nodes/:url
GET {{baseUrl}}/nodes/:url