### REST Client for Visual Studio Code "ext install humao.rest-client" ###

@baseUrl = http://localhost:3333

### Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name":"Bruno S. Duarte",
  "email": "brunosdua@dev.br",
  "password": "123456"
}

### Authenticate
# @name authenticated
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "brunosdua@dev.br",
  "password": "123456"
}

### you need authenticate to obtain token
@token = {{authenticated.response.body.token}}

### Profile
GET {{baseUrl}}/me HTTP/1.1
Authorization: Bearer {{token}}

### @/nodes/:url
GET {{baseUrl}}/nodes/:url

